### ISSUE TITLE
Is mclust supposed to be slow?

### ISSUE THREAD

**Issue by peterkilfeather** [JinmiaoChenLab/GraphST#15]
I'm running tutorial 3 (https://deepst-tutorials.readthedocs.io/en/latest/Tutorial%203_Stereo-seq.html).

The clustering stage takes a long time to process when using `mclust`. It is stuck at the 'fitting... 0%' stage. `leiden` take only a few seconds.

Is this normal? htop is reporting 12 threads being used, so it is doing something...

**Comment by sokratiag** [comment]
Hi, 

I am having the same issue - could you please share how you solved it? Thanks!
