### ISSUE TITLE
The different results when i tried to cluster DLPFC with GraphST

### ISSUE THREAD

**Issue by tqwang743** [JinmiaoChenLab/GraphST#7]
Hi Jinmiao,

 It is a fantastic method for analyzing spatial transcriptomics!

I tried to cluster DLPFC samples with GraphST following the tutorial 1 you present . I found the outcomes are quite different from the results in the paper. I use the same  GPU RTXA6000. the following picture is the result I got . 
<img width="411" alt="image" src="https://user-images.githubusercontent.com/108932740/222951644-6893340b-6933-485b-a5da-c1bf956495f5.png">

Best,
tqwang

**Comment by longyahui** [comment]
Hi tqwang,

     Thank you for your attention on our work.

     This dataset is not 151673. Could you help share me the real results please? My email is long_yahui@immunol.a-star.edu.sg. Thanks.

     Best regards,
     Yahui

**Comment by tqwang743** [comment]
Thank you for help！I find that i truly use the wrong dataset. The following picture is the result I got in 156173 dataset. It is very close to the result in the paper!
![image](https://user-images.githubusercontent.com/108932740/223009343-25429116-1d7b-4518-854b-1b5e6515d60b.png)

**Comment by longyahui** [comment]
Thanks tqwang for sharing the reproduced results.
